### ISSUE TITLE
How to Get the Tamperd Region

### ISSUE THREAD

**Issue by ncuxiaogang** [dbisUnibas/PS-Battles#1]
Thanks for your PS-Battles dataset. Recently I want to use your dataset for training and I want to use the mask of the tampered region, and I read the 'photoshops.csv' carefully. I can not get the originally untampered image. Would you please release the Tampered-Mask or the Un-Tampered images so I can get the Maks through minus operation. Thanks very much.

Best Regards!

**Comment by lucaro** [comment]
Hey,

The untampered images can be found in the originals.tsv. There are no 'regions' in the dataset since many of the modifications could not adequately be described by just a mask, some of them spanning the entire image in one way or the other.
